package com.lagradost.cloudstream3.shared.ui.player

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.Icon
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AspectRatio
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.VideoLibrary
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.lagradost.cloudstream4.generated.resources.*
import com.lagradost.cloudstream3.shared.ui.components.MediaBadge
import com.lagradost.cloudstream3.shared.ui.components.designsystem.ActionDialog
import com.lagradost.cloudstream3.shared.ui.components.designsystem.BodyMutedText
import com.lagradost.cloudstream3.shared.ui.components.designsystem.CloudStreamTextField
import com.lagradost.cloudstream3.shared.ui.components.designsystem.SelectableOptionCard
import com.lagradost.cloudstream3.shared.ui.theme.CloudStreamColors
import com.lagradost.cloudstream3.shared.ui.theme.CloudStreamTheme
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerActiveModal
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerAspectRatio
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerAudioTrack
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerEpisode
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerQuality
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerSubtitleTrack
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerUiEvent
import com.lagradost.cloudstream3.shared.viewmodels.player.PlayerUiState
import kotlinx.collections.immutable.ImmutableList
import kotlinx.collections.immutable.persistentListOf
import org.jetbrains.compose.resources.StringResource
import org.jetbrains.compose.resources.painterResource
import org.jetbrains.compose.resources.stringResource
import org.jetbrains.compose.ui.tooling.preview.Preview
import kotlin.math.abs

private val SPEED_OPTIONS = listOf(0.5f, 0.75f, 1.0f, 1.25f, 1.5f, 1.75f, 2.0f)

private fun resolveQualityBadgeColor(effectiveRes: Int): Color = when {
    effectiveRes >= 2160 -> CloudStreamColors.Quality4K
    effectiveRes >= 1080 -> CloudStreamColors.QualityHD
    effectiveRes >= 720 -> CloudStreamColors.QualityHQ
    else -> CloudStreamColors.QualitySD
}

private fun filterSubtitles(
    subtitles: ImmutableList<PlayerSubtitleTrack>,
    query: String
): List<PlayerSubtitleTrack> {
    if (query.isBlank()) return subtitles
    return subtitles.filter { track ->
        track.name.contains(query, ignoreCase = true) ||
                track.languageCode?.contains(query, ignoreCase = true) == true
    }
}

private fun resolveSubtitleDescription(
    track: PlayerSubtitleTrack,
    onlineLabel: String,
    embeddedLabel: String
): String {
    track.languageCode?.takeIf { it.isNotBlank() }?.let { return it }
    return if (track.isAutoGenerated) onlineLabel else embeddedLabel
}

private fun filterEpisodes(
    playlist: ImmutableList<PlayerEpisode>,
    query: String
): List<IndexedValue<PlayerEpisode>> {
    val indexedList = playlist.withIndex().toList()
    if (query.isBlank()) return indexedList
    return indexedList.filter { (_, ep) ->
        val epName = ep.name.orEmpty()
        val epNum = ep.episodeNumber?.toString().orEmpty()
        epName.contains(query, ignoreCase = true) || epNum.contains(query)
    }
}

private fun resolveEpisodeSubtitle(
    ep: PlayerEpisode,
    seasonShort: String,
    episodeShort: String
): String {
    return buildString {
        if (ep.seasonNumber != null && ep.seasonNumber > 0) {
            append("$seasonShort${ep.seasonNumber} ")
        }
        if (ep.episodeNumber != null) {
            append("$episodeShort${ep.episodeNumber}")
        }
    }
}

private fun resolveAspectRatioStrings(ratio: PlayerAspectRatio): Pair<StringResource, StringResource> {
    return when (ratio) {
        PlayerAspectRatio.Fit -> Res.string.aspect_ratio_fit to Res.string.aspect_ratio_fit
        PlayerAspectRatio.Zoom -> Res.string.aspect_ratio_zoom to Res.string.aspect_ratio_zoom
        PlayerAspectRatio.Stretch -> Res.string.aspect_ratio_stretch to Res.string.aspect_ratio_stretch
        PlayerAspectRatio.Original -> Res.string.aspect_ratio_original to Res.string.aspect_ratio_original
    }
}

@Composable
fun PlayerQualitySourcesModal(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    ActionDialog(
        onDismissRequest = onDismiss,
        titleRes = Res.string.video_quality,
        icon = {
            Icon(
                painter = painterResource(Res.drawable.ic_baseline_hd_24),
                contentDescription = stringResource(Res.string.quality),
                tint = CloudStreamColors.Primary,
                modifier = Modifier.size(24.dp)
            )
        },
        showCloseButton = true,
        confirmTextRes = Res.string.close,
        onConfirm = onDismiss,
        content = {
            if (state.availableQualities.isEmpty()) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 24.dp),
                    contentAlignment = Alignment.Center
                ) {
                    BodyMutedText(text = stringResource(Res.string.no_qualities_available))
                }
            } else {
                LazyColumn(
                    verticalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier
                        .fillMaxWidth()
                        .heightIn(max = 340.dp)
                ) {
                    items(state.availableQualities) { quality ->
                        val isSelected = quality.url == state.currentUrl ||
                                quality == state.selectedQuality ||
                                quality.id == state.selectedQuality?.id ||
                                (quality.isAuto && state.selectedQuality == null)

                        QualityOptionCard(
                            quality = quality,
                            isSelected = isSelected,
                            onClick = {
                                onEvent(PlayerUiEvent.SelectQuality(quality))
                                onEvent(PlayerUiEvent.SetActiveModal(null))
                            }
                        )
                    }
                }
            }
        }
    )
}

@Composable
private fun QualityOptionCard(
    quality: PlayerQuality,
    isSelected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val effectiveRes = quality.effectiveResolution
    val badgeColor = resolveQualityBadgeColor(effectiveRes)
    val qualityLabel = if (effectiveRes > 1) "${effectiveRes}p" else stringResource(Res.string.quality_auto)

    SelectableOptionCard(
        isSelected = isSelected,
        title = quality.name.ifBlank { qualityLabel },
        leadingContent = {
            MediaBadge(
                text = qualityLabel,
                backgroundColor = badgeColor,
                textColor = CloudStreamColors.OnMediaScrim
            )
        },
        onClick = onClick,
        modifier = modifier
    )
}

@Composable
fun PlayerSubtitlesModal(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    var searchQuery by remember { mutableStateOf("") }
    val filteredSubtitles = remember(state.availableSubtitles, searchQuery) {
        filterSubtitles(state.availableSubtitles, searchQuery)
    }

    ActionDialog(
        onDismissRequest = onDismiss,
        titleRes = Res.string.subtitles,
        icon = {
            Icon(
                painter = painterResource(Res.drawable.ic_outline_subtitles_24),
                contentDescription = stringResource(Res.string.subtitles),
                tint = CloudStreamColors.Secondary,
                modifier = Modifier.size(24.dp)
            )
        },
        showCloseButton = true,
        confirmTextRes = Res.string.close,
        onConfirm = onDismiss,
        content = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 380.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                if (state.availableSubtitles.size > 5) {
                    CloudStreamTextField(
                        value = searchQuery,
                        onValueChange = { searchQuery = it },
                        placeholder = stringResource(Res.string.search),
                        leadingIconVector = Icons.Default.Search,
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )
                }

                if (searchQuery.isBlank()) {
                    SubtitleOffOptionCard(
                        isSelected = state.selectedSubtitle == null,
                        onClick = {
                            onEvent(PlayerUiEvent.SelectSubtitle(null))
                            onEvent(PlayerUiEvent.SetActiveModal(null))
                        }
                    )
                }

                SubtitleListContent(
                    subtitles = filteredSubtitles,
                    selectedSubtitle = state.selectedSubtitle,
                    isSearching = searchQuery.isNotBlank(),
                    onSelect = { subtitle ->
                        onEvent(PlayerUiEvent.SelectSubtitle(subtitle))
                        onEvent(PlayerUiEvent.SetActiveModal(null))
                    }
                )
            }
        }
    )
}

@Composable
private fun SubtitleOffOptionCard(
    isSelected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    SelectableOptionCard(
        isSelected = isSelected,
        titleRes = Res.string.noSubtitles,
        accentColor = CloudStreamColors.Secondary,
        onClick = onClick,
        modifier = modifier
    )
}

@Composable
private fun SubtitleListContent(
    subtitles: List<PlayerSubtitleTrack>,
    selectedSubtitle: PlayerSubtitleTrack?,
    isSearching: Boolean,
    onSelect: (PlayerSubtitleTrack) -> Unit,
    modifier: Modifier = Modifier
) {
    if (subtitles.isEmpty() && isSearching) {
        Box(
            modifier = modifier
                .fillMaxWidth()
                .padding(vertical = 16.dp),
            contentAlignment = Alignment.Center
        ) {
            BodyMutedText(text = stringResource(Res.string.no_subtitles_loaded))
        }
    } else if (subtitles.isNotEmpty()) {
        LazyColumn(
            verticalArrangement = Arrangement.spacedBy(8.dp),
            modifier = modifier
                .fillMaxWidth()
                .heightIn(max = 300.dp)
        ) {
            items(subtitles) { subtitle ->
                val isSelected = subtitle == selectedSubtitle || subtitle.id == selectedSubtitle?.id
                SubtitleOptionCard(
                    track = subtitle,
                    isSelected = isSelected,
                    onClick = { onSelect(subtitle) }
                )
            }
        }
    }
}

@Composable
private fun SubtitleOptionCard(
    track: PlayerSubtitleTrack,
    isSelected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val onlineLabel = stringResource(Res.string.subtitles_from_online)
    val embeddedLabel = stringResource(Res.string.subtitles_from_embedded)
    val description = resolveSubtitleDescription(track, onlineLabel, embeddedLabel)

    SelectableOptionCard(
        isSelected = isSelected,
        title = track.name,
        subtitle = description,
        accentColor = CloudStreamColors.Secondary,
        onClick = onClick,
        modifier = modifier
    )
}

@Composable
fun PlayerAudioTracksModal(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    ActionDialog(
        onDismissRequest = onDismiss,
        titleRes = Res.string.audio_tracks_dialog_title,
        icon = {
            Icon(
                painter = painterResource(Res.drawable.ic_baseline_volume_up_24),
                contentDescription = stringResource(Res.string.audio_tracks_dialog_title),
                tint = CloudStreamColors.Primary,
                modifier = Modifier.size(24.dp)
            )
        },
        showCloseButton = true,
        confirmTextRes = Res.string.close,
        onConfirm = onDismiss,
        content = {
            if (state.availableAudioTracks.isEmpty()) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 24.dp),
                    contentAlignment = Alignment.Center
                ) {
                    BodyMutedText(text = stringResource(Res.string.no_audio_tracks_available))
                }
            } else {
                LazyColumn(
                    verticalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier
                        .fillMaxWidth()
                        .heightIn(max = 340.dp)
                ) {
                    items(state.availableAudioTracks) { track ->
                        val isSelected = track == state.selectedAudioTrack || track.id == state.selectedAudioTrack?.id

                        AudioTrackOptionCard(
                            track = track,
                            isSelected = isSelected,
                            onClick = {
                                onEvent(PlayerUiEvent.SelectAudioTrack(track))
                                onEvent(PlayerUiEvent.SetActiveModal(null))
                            }
                        )
                    }
                }
            }
        }
    )
}

@Composable
private fun AudioTrackOptionCard(
    track: PlayerAudioTrack,
    isSelected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val defaultTitle = stringResource(Res.string.audio_singular)
    SelectableOptionCard(
        isSelected = isSelected,
        title = track.name.ifBlank { defaultTitle },
        subtitle = track.languageCode?.takeIf { it.isNotBlank() },
        onClick = onClick,
        modifier = modifier
    )
}

@Composable
fun PlayerSpeedModal(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    ActionDialog(
        onDismissRequest = onDismiss,
        titleRes = Res.string.playback_speed,
        icon = {
            Icon(
                painter = painterResource(Res.drawable.ic_baseline_speed_24),
                contentDescription = stringResource(Res.string.speed),
                tint = CloudStreamColors.Primary,
                modifier = Modifier.size(24.dp)
            )
        },
        showCloseButton = true,
        confirmTextRes = Res.string.close,
        onConfirm = onDismiss,
        content = {
            LazyColumn(
                verticalArrangement = Arrangement.spacedBy(8.dp),
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 340.dp)
            ) {
                items(SPEED_OPTIONS) { speed ->
                    val isSelected = abs(state.playbackSpeed - speed) < 0.01f
                    SpeedOptionCard(
                        speed = speed,
                        isSelected = isSelected,
                        onClick = {
                            onEvent(PlayerUiEvent.SetSpeed(speed))
                            onEvent(PlayerUiEvent.SetActiveModal(null))
                        }
                    )
                }
            }
        }
    )
}

@Composable
private fun SpeedOptionCard(
    speed: Float,
    isSelected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val label = if (speed == 1.0f) stringResource(Res.string.speed_normal) else "${speed}x"
    SelectableOptionCard(
        isSelected = isSelected,
        title = label,
        onClick = onClick,
        modifier = modifier
    )
}

@Composable
fun PlayerEpisodesModal(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    var searchQuery by remember { mutableStateOf("") }
    val filteredPlaylist = remember(state.playlist, searchQuery) {
        filterEpisodes(state.playlist, searchQuery)
    }
    val listState = rememberLazyListState()

    LaunchedEffect(state.currentEpisodeIndex) {
        if (state.currentEpisodeIndex in state.playlist.indices) {
            val targetIndex = filteredPlaylist.indexOfFirst { it.index == state.currentEpisodeIndex }
            if (targetIndex >= 0) {
                listState.animateScrollToItem(targetIndex)
            }
        }
    }

    ActionDialog(
        onDismissRequest = onDismiss,
        titleRes = Res.string.episodes,
        iconVector = Icons.Default.VideoLibrary,
        showCloseButton = true,
        confirmTextRes = Res.string.close,
        onConfirm = onDismiss,
        content = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 380.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                if (state.playlist.size > 5) {
                    CloudStreamTextField(
                        value = searchQuery,
                        onValueChange = { searchQuery = it },
                        placeholder = stringResource(Res.string.search_episodes_hint),
                        leadingIconVector = Icons.Default.Search,
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )
                }

                if (filteredPlaylist.isEmpty()) {
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(24.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        BodyMutedText(text = stringResource(Res.string.no_episodes_available))
                    }
                } else {
                    LazyColumn(
                        state = listState,
                        verticalArrangement = Arrangement.spacedBy(8.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .weight(1f, fill = false)
                    ) {
                        items(filteredPlaylist, key = { it.value.id }) { indexedEp ->
                            val isSelected = indexedEp.index == state.currentEpisodeIndex ||
                                    indexedEp.value.id == state.currentEpisode?.id

                            EpisodeOptionCard(
                                indexedEpisode = indexedEp,
                                isSelected = isSelected,
                                onClick = {
                                    onEvent(PlayerUiEvent.SelectEpisode(indexedEp.index))
                                    onEvent(PlayerUiEvent.SetActiveModal(null))
                                }
                            )
                        }
                    }
                }
            }
        }
    )
}

@Composable
private fun EpisodeOptionCard(
    indexedEpisode: IndexedValue<PlayerEpisode>,
    isSelected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val (originalIndex, ep) = indexedEpisode
    val episodeWord = stringResource(Res.string.episode)
    val seasonShort = stringResource(Res.string.season_short)
    val episodeShort = stringResource(Res.string.episode_short)

    val episodeTitle = ep.name ?: "$episodeWord ${ep.episodeNumber ?: (originalIndex + 1)}"
    val subtitle = resolveEpisodeSubtitle(ep, seasonShort, episodeShort)

    SelectableOptionCard(
        isSelected = isSelected,
        title = episodeTitle,
        subtitle = subtitle.takeIf { it.isNotBlank() },
        leadingContent = if (isSelected) {
            {
                MediaBadge(
                    text = stringResource(Res.string.playing),
                    backgroundColor = CloudStreamColors.Primary,
                    textColor = CloudStreamColors.OnMediaScrim
                )
            }
        } else null,
        onClick = onClick,
        modifier = modifier
    )
}

@Composable
fun PlayerAspectRatioModal(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    ActionDialog(
        onDismissRequest = onDismiss,
        titleRes = Res.string.aspect_ratio,
        iconVector = Icons.Default.AspectRatio,
        showCloseButton = true,
        confirmTextRes = Res.string.close,
        onConfirm = onDismiss,
        content = {
            LazyColumn(
                verticalArrangement = Arrangement.spacedBy(8.dp),
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 340.dp)
            ) {
                items(PlayerAspectRatio.entries) { ratio ->
                    val isSelected = state.aspectRatio == ratio
                    val (titleRes, descRes) = resolveAspectRatioStrings(ratio)

                    SelectableOptionCard(
                        isSelected = isSelected,
                        titleRes = titleRes,
                        subtitleRes = descRes,
                        onClick = {
                            onEvent(PlayerUiEvent.SetAspectRatio(ratio))
                            onEvent(PlayerUiEvent.SetActiveModal(null))
                        }
                    )
                }
            }
        }
    )
}

@Composable
fun PlayerActiveModals(
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit = { onEvent(PlayerUiEvent.SetActiveModal(null)) }
) {
    val modal = state.activeModal ?: return
    if (renderMediaSelectionModal(modal, state, onEvent, onDismiss)) return
    renderPlaybackSettingsModal(modal, state, onEvent, onDismiss)
}

@Composable
private fun renderMediaSelectionModal(
    modal: PlayerActiveModal,
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit
): Boolean {
    when (modal) {
        PlayerActiveModal.QUALITY_SOURCES -> PlayerQualitySourcesModal(state, onEvent, onDismiss)
        PlayerActiveModal.SUBTITLES -> PlayerSubtitlesModal(state, onEvent, onDismiss)
        PlayerActiveModal.AUDIO_TRACKS -> PlayerAudioTracksModal(state, onEvent, onDismiss)
        else -> return false
    }
    return true
}

@Composable
private fun renderPlaybackSettingsModal(
    modal: PlayerActiveModal,
    state: PlayerUiState,
    onEvent: (PlayerUiEvent) -> Unit,
    onDismiss: () -> Unit
) {
    when (modal) {
        PlayerActiveModal.SPEED -> PlayerSpeedModal(state, onEvent, onDismiss)
        PlayerActiveModal.EPISODES -> PlayerEpisodesModal(state, onEvent, onDismiss)
        PlayerActiveModal.SETTINGS -> PlayerAspectRatioModal(state, onEvent, onDismiss)
        else -> Unit
    }
}

@Preview
@Composable
private fun PlayerQualitySourcesModalPreview() {
    CloudStreamTheme {
        PlayerQualitySourcesModal(
            state = PlayerUiState(
                availableQualities = persistentListOf(
                    PlayerQuality(name = "1080p", quality = 1080),
                    PlayerQuality(name = "720p", quality = 720)
                )
            ),
            onEvent = {}
        )
    }
}

@Preview
@Composable
private fun PlayerSubtitlesModalPreview() {
    CloudStreamTheme {
        PlayerSubtitlesModal(
            state = PlayerUiState(
                availableSubtitles = persistentListOf(
                    PlayerSubtitleTrack(name = "English", languageCode = "en"),
                    PlayerSubtitleTrack(name = "Spanish", languageCode = "es")
                )
            ),
            onEvent = {}
        )
    }
}

@Preview
@Composable
private fun PlayerAudioTracksModalPreview() {
    CloudStreamTheme {
        PlayerAudioTracksModal(
            state = PlayerUiState(
                availableAudioTracks = persistentListOf(
                    PlayerAudioTrack(name = "English", languageCode = "en"),
                    PlayerAudioTrack(name = "Japanese", languageCode = "ja")
                )
            ),
            onEvent = {}
        )
    }
}

@Preview
@Composable
private fun PlayerSpeedModalPreview() {
    CloudStreamTheme {
        PlayerSpeedModal(
            state = PlayerUiState(playbackSpeed = 1.0f),
            onEvent = {}
        )
    }
}

@Preview
@Composable
private fun PlayerEpisodesModalPreview() {
    CloudStreamTheme {
        PlayerEpisodesModal(
            state = PlayerUiState(
                playlist = persistentListOf(
                    PlayerEpisode(id = 1, name = "Episode 1", episodeNumber = 1),
                    PlayerEpisode(id = 2, name = "Episode 2", episodeNumber = 2)
                )
            ),
            onEvent = {}
        )
    }
}

@Preview
@Composable
private fun PlayerAspectRatioModalPreview() {
    CloudStreamTheme {
        PlayerAspectRatioModal(
            state = PlayerUiState(aspectRatio = PlayerAspectRatio.Fit),
            onEvent = {}
        )
    }
}
