package com.lagradost.cloudstream3.shared.viewmodels.player

import androidx.compose.runtime.Immutable
import com.lagradost.cloudstream3.SubtitleFile
import com.lagradost.cloudstream3.shared.mvi.UiState
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.Qualities
import kotlinx.collections.immutable.ImmutableList
import kotlinx.collections.immutable.ImmutableMap
import kotlinx.collections.immutable.persistentListOf
import kotlinx.collections.immutable.persistentMapOf
import kotlinx.collections.immutable.toImmutableMap
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

private val RESOLUTION_MATCHERS = listOf(
    listOf("2160", "4k", "uhd") to 2160,
    listOf("1440", "2k", "qhd") to 1440,
    listOf("1080", "fhd") to 1080,
    listOf("720", "hd") to 720,
    listOf("480", "sd") to 480,
    listOf("360") to 360,
    listOf("240") to 240,
    listOf("144") to 144
)

private fun parseResolutionFromText(text: String): Int? {
    for ((keywords, resolution) in RESOLUTION_MATCHERS) {
        if (keywords.any { it in text }) return resolution
    }
    return null
}

@Immutable
@Serializable
data class PlayerQuality(
    val id: String = "",
    val name: String = "",
    val quality: Int = 0,
    val url: String = "",
    val headers: ImmutableMap<String, String> = persistentMapOf(),
    val isAuto: Boolean = false,
    @Transient val extractorLink: ExtractorLink? = null
) {
    val effectiveResolution: Int
        get() {
            if (quality > 0 && quality != Qualities.Unknown.value) return quality
            val text = "$name $id".lowercase()
            parseResolutionFromText(text)?.let { return it }
            return when {
                quality == Qualities.Unknown.value -> 1
                isAuto || quality == 0 -> 0
                else -> quality
            }
        }

    companion object {
        val Auto = PlayerQuality(id = "auto", name = "Auto", quality = 0, url = "", isAuto = true)

        fun fromExtractorLink(link: ExtractorLink): PlayerQuality {
            val allHeaders = mutableMapOf<String, String>()
            if (link.referer.isNotBlank()) {
                allHeaders["Referer"] = link.referer
            }
            allHeaders.putAll(link.headers)
            return PlayerQuality(
                id = "${link.source}_${link.name}_${link.quality}",
                name = link.name,
                quality = link.quality,
                url = link.url,
                headers = allHeaders.toImmutableMap(),
                isAuto = link.quality == 0,
                extractorLink = link
            )
        }
    }
}

@Immutable
@Serializable
data class PlayerSubtitleTrack(
    val id: String = "",
    val name: String = "",
    val languageCode: String? = null,
    val url: String = "",
    val headers: ImmutableMap<String, String> = persistentMapOf(),
    val isAutoGenerated: Boolean = false,
    val isDefault: Boolean = false,
    @Transient val subtitleFile: SubtitleFile? = null
) {
    companion object {
        fun fromSubtitleFile(file: SubtitleFile, isDefault: Boolean = false): PlayerSubtitleTrack {
            return PlayerSubtitleTrack(
                id = file.url,
                name = file.lang,
                languageCode = file.langTag,
                url = file.url,
                headers = (file.headers ?: emptyMap()).toImmutableMap(),
                isAutoGenerated = false,
                isDefault = isDefault,
                subtitleFile = file
            )
        }
    }
}

enum class PlayerSkipType {
    Opening,
    Ending,
    Recap,
    MixedOpening,
    MixedEnding,
    Credits,
    Intro,
    Preview,
    Custom
}

@Immutable
@Serializable
data class PlayerSkipTimestamp(
    val type: PlayerSkipType = PlayerSkipType.Intro,
    val startMs: Long,
    val endMs: Long,
    val label: String? = null
) {
    val isIntro: Boolean
        get() = type == PlayerSkipType.Opening ||
                type == PlayerSkipType.Intro ||
                type == PlayerSkipType.Recap ||
                type == PlayerSkipType.MixedOpening

    val isOutro: Boolean
        get() = type == PlayerSkipType.Ending ||
                type == PlayerSkipType.Credits ||
                type == PlayerSkipType.MixedEnding ||
                type == PlayerSkipType.Preview

    fun contains(posMs: Long): Boolean = posMs in startMs..endMs
}

enum class PlayerAspectRatio {
    Fit, Zoom, Stretch, Original
}

@Immutable
@Serializable
data class PlayerEpisode(
    val id: Int,
    val name: String? = null,
    val episodeNumber: Int? = null,
    val seasonNumber: Int? = null,
    val description: String? = null,
    val posterUrl: String? = null,
    val qualities: ImmutableList<PlayerQuality> = persistentListOf(),
    val subtitles: ImmutableList<PlayerSubtitleTrack> = persistentListOf(),
    val skipTimestamps: ImmutableList<PlayerSkipTimestamp> = persistentListOf()
) {
    val episode: Int? get() = episodeNumber
    val season: Int? get() = seasonNumber
}

@Immutable
@Serializable
data class PlayerAudioTrack(
    val id: String = "",
    val name: String = "",
    val languageCode: String? = null,
    val isDefault: Boolean = false
)

enum class PlayerActiveModal {
    QUALITY_SOURCES,
    SUBTITLES,
    AUDIO_TRACKS,
    SPEED,
    EPISODES,
    SETTINGS
}

enum class LockPinDialogMode {
    Lock, Unlock
}

@Immutable
data class PlayerUiState(
    val isPlaying: Boolean = false,
    val isBuffering: Boolean = false,
    val isStopped: Boolean = true,
    val positionMs: Long = 0L,
    val durationMs: Long = 0L,
    val currentUrl: String? = null,
    val availableQualities: ImmutableList<PlayerQuality> = persistentListOf(),
    val selectedQuality: PlayerQuality? = null,
    val availableSubtitles: ImmutableList<PlayerSubtitleTrack> = persistentListOf(),
    val selectedSubtitle: PlayerSubtitleTrack? = null,
    val availableAudioTracks: ImmutableList<PlayerAudioTrack> = persistentListOf(),
    val selectedAudioTrack: PlayerAudioTrack? = null,
    val playbackSpeed: Float = 1.0f,
    val aspectRatio: PlayerAspectRatio = PlayerAspectRatio.Fit,
    val subtitleDelayMs: Long = 0L,
    val audioDelayMs: Long = 0L,
    val areControlsVisible: Boolean = true,
    val activeModal: PlayerActiveModal? = null,
    val isControlsLocked: Boolean = false,
    val lockPin: String? = null,
    val isPinLocked: Boolean = false,
    val showLockPinDialog: Boolean = false,
    val lockPinDialogMode: LockPinDialogMode = LockPinDialogMode.Unlock,
    val skipTimestamps: ImmutableList<PlayerSkipTimestamp> = persistentListOf(),
    val activeSkipTimestamp: PlayerSkipTimestamp? = null,
    val accountId: Int = 0,
    val parentId: Int? = null,
    val currentEpisodeId: Int? = null,
    val currentEpisode: PlayerEpisode? = null,
    val playlist: ImmutableList<PlayerEpisode> = persistentListOf(),
    val currentEpisodeIndex: Int = 0,
    val hasNextEpisode: Boolean = false,
    val hasPreviousEpisode: Boolean = false,
    val errorMessage: String? = null
) : UiState {
    val progressPercentage: Float
        get() = if (durationMs > 0L) (positionMs.toFloat() / durationMs.toFloat()).coerceIn(0f, 1f) else 0f

    val formattedPosition: String
        get() = formatTime(positionMs)

    val formattedDuration: String
        get() = formatTime(durationMs)

    companion object {
        fun formatTime(millis: Long): String {
            val totalSeconds = (millis / 1000).coerceAtLeast(0)
            val seconds = totalSeconds % 60
            val minutes = (totalSeconds / 60) % 60
            val hours = totalSeconds / 3600
            return if (hours > 0) {
                "${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}"
            } else {
                "${minutes}:${seconds.toString().padStart(2, '0')}"
            }
        }
    }
}
