package com.lagradost.cloudstream3.shared.viewmodels.player

import com.lagradost.cloudstream3.SubtitleFile
import com.lagradost.cloudstream3.shared.mvi.UiState
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.Qualities
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

/**
 * Quality track available for playback in the player.
 */
@Serializable
data class PlayerQuality(
    val id: String = "",
    val name: String = "",
    val quality: Int = 0,
    val url: String = "",
    val headers: Map<String, String> = emptyMap(),
    val isAuto: Boolean = false,
    @Transient val extractorLink: ExtractorLink? = null
) {
    /**
     * Effective numerical resolution in pixels (e.g. 2160, 1440, 1080, 720, 480, 360, 240, 144)
     * used for deterministic sorting and automatic selection of optimal quality.
     */
    val effectiveResolution: Int
        get() {
            if (quality > 0 && quality != Qualities.Unknown.value) {
                return quality
            }
            val text = "$name $id".lowercase()
            return when {
                "2160" in text || "4k" in text || "uhd" in text -> 2160
                "1440" in text || "2k" in text || "qhd" in text -> 1440
                "1080" in text || "fhd" in text -> 1080
                "720" in text || "hd" in text -> 720
                "480" in text || "sd" in text -> 480
                "360" in text -> 360
                "240" in text -> 240
                "144" in text -> 144
                quality == Qualities.Unknown.value -> 1
                isAuto || quality == 0 -> 0
                else -> quality
            }
        }

    companion object {
        val Auto = PlayerQuality(id = "auto", name = "Auto", quality = 0, url = "", isAuto = true)

        fun fromExtractorLink(link: ExtractorLink): PlayerQuality {
            val allHeaders = mutableMapOf<String, String>()
            if (link.referer.isNotBlank()) {
                allHeaders["Referer"] = link.referer
            }
            allHeaders.putAll(link.headers)
            return PlayerQuality(
                id = "${link.source}_${link.name}_${link.quality}",
                name = link.name,
                quality = link.quality,
                url = link.url,
                headers = allHeaders,
                isAuto = link.quality == 0,
                extractorLink = link
            )
        }
    }
}

/**
 * Subtitle track available for the media.
 */
@Serializable
data class PlayerSubtitleTrack(
    val id: String = "",
    val name: String = "",
    val languageCode: String? = null,
    val url: String = "",
    val headers: Map<String, String> = emptyMap(),
    val isAutoGenerated: Boolean = false,
    val isDefault: Boolean = false,
    @Transient val subtitleFile: SubtitleFile? = null
) {
    companion object {
        fun fromSubtitleFile(file: SubtitleFile, isDefault: Boolean = false): PlayerSubtitleTrack {
            return PlayerSubtitleTrack(
                id = file.url,
                name = file.lang,
                languageCode = file.langTag,
                url = file.url,
                headers = file.headers ?: emptyMap(),
                isAutoGenerated = false,
                isDefault = isDefault,
                subtitleFile = file
            )
        }
    }
}

/**
 * Type of skip segment (opening, ending, recap, etc.).
 */
enum class PlayerSkipType {
    Opening,
    Ending,
    Recap,
    MixedOpening,
    MixedEnding,
    Credits,
    Intro,
    Preview,
    Custom
}

/**
 * Timestamp marker for skipping intro/outro/recap/credits in video playback.
 */
@Serializable
data class PlayerSkipTimestamp(
    val type: PlayerSkipType = PlayerSkipType.Intro,
    val startMs: Long,
    val endMs: Long,
    val label: String? = null
) {
    val isIntro: Boolean
        get() = type == PlayerSkipType.Opening ||
                type == PlayerSkipType.Intro ||
                type == PlayerSkipType.Recap ||
                type == PlayerSkipType.MixedOpening

    val isOutro: Boolean
        get() = type == PlayerSkipType.Ending ||
                type == PlayerSkipType.Credits ||
                type == PlayerSkipType.MixedEnding ||
                type == PlayerSkipType.Preview

    fun contains(posMs: Long): Boolean = posMs in startMs..endMs
}


/**
 * Video scaling / aspect ratio modes.
 */
enum class PlayerAspectRatio {
    Fit, Zoom, Stretch, Original
}

/**
 * Metadata representing a playable episode or media item.
 */
@Serializable
data class PlayerEpisode(
    val id: Int,
    val name: String? = null,
    val episodeNumber: Int? = null,
    val seasonNumber: Int? = null,
    val description: String? = null,
    val posterUrl: String? = null,
    val qualities: List<PlayerQuality> = emptyList(),
    val subtitles: List<PlayerSubtitleTrack> = emptyList(),
    val skipTimestamps: List<PlayerSkipTimestamp> = emptyList()
) {
    val episode: Int? get() = episodeNumber
    val season: Int? get() = seasonNumber
}

/**
 * Model representing an audio stream track.
 */
@Serializable
data class PlayerAudioTrack(
    val id: String = "",
    val name: String = "",
    val languageCode: String? = null,
    val isDefault: Boolean = false
)

/**
 * Active modal/sheet displayed in the player overlay.
 */
enum class PlayerActiveModal {
    QUALITY_SOURCES,
    SUBTITLES,
    AUDIO_TRACKS,
    SPEED,
    EPISODES,
    SETTINGS
}

/**
 * Mode for the Lock PIN Dialog.
 */
enum class LockPinDialogMode {
    Lock, Unlock
}

/**
 * Immutable UI state for the video player controller (MVI pattern).
 */
data class PlayerUiState(
    val isPlaying: Boolean = false,
    val isBuffering: Boolean = false,
    val isStopped: Boolean = true,
    val positionMs: Long = 0L,
    val durationMs: Long = 0L,
    val currentUrl: String? = null,
    val availableQualities: List<PlayerQuality> = emptyList(),
    val selectedQuality: PlayerQuality? = null,
    val availableSubtitles: List<PlayerSubtitleTrack> = emptyList(),
    val selectedSubtitle: PlayerSubtitleTrack? = null,
    val availableAudioTracks: List<PlayerAudioTrack> = emptyList(),
    val selectedAudioTrack: PlayerAudioTrack? = null,
    val playbackSpeed: Float = 1.0f,
    val aspectRatio: PlayerAspectRatio = PlayerAspectRatio.Fit,
    val subtitleDelayMs: Long = 0L,
    val audioDelayMs: Long = 0L,
    val areControlsVisible: Boolean = true,
    val activeModal: PlayerActiveModal? = null,
    val isControlsLocked: Boolean = false,
    val lockPin: String? = null,
    val isPinLocked: Boolean = false,
    val showLockPinDialog: Boolean = false,
    val lockPinDialogMode: LockPinDialogMode = LockPinDialogMode.Unlock,
    val skipTimestamps: List<PlayerSkipTimestamp> = emptyList(),
    val activeSkipTimestamp: PlayerSkipTimestamp? = null,
    val accountId: Int = 0,
    val parentId: Int? = null,
    val currentEpisodeId: Int? = null,
    val currentEpisode: PlayerEpisode? = null,
    val playlist: List<PlayerEpisode> = emptyList(),
    val currentEpisodeIndex: Int = 0,
    val hasNextEpisode: Boolean = false,
    val hasPreviousEpisode: Boolean = false,
    val errorMessage: String? = null
) : UiState {
    val progressPercentage: Float
        get() = if (durationMs > 0L) (positionMs.toFloat() / durationMs.toFloat()).coerceIn(0f, 1f) else 0f

    val formattedPosition: String
        get() = formatTime(positionMs)

    val formattedDuration: String
        get() = formatTime(durationMs)

    companion object {
        fun formatTime(millis: Long): String {
            val totalSeconds = (millis / 1000).coerceAtLeast(0)
            val seconds = totalSeconds % 60
            val minutes = (totalSeconds / 60) % 60
            val hours = totalSeconds / 3600
            return if (hours > 0) {
                "${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}"
            } else {
                "${minutes}:${seconds.toString().padStart(2, '0')}"
            }
        }
    }
}
