package com.lagradost.cloudstream3.plugins

import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.intOrNull

object PluginStatusIntSerializer : KSerializer<Int> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("PluginStatusInt", PrimitiveKind.INT)
    override fun serialize(encoder: Encoder, value: Int) = encoder.encodeInt(value)
    override fun deserialize(decoder: Decoder): Int {
        val jsonDecoder = decoder as? JsonDecoder
        if (jsonDecoder != null) {
            val element = runCatching { jsonDecoder.decodeJsonElement() }.getOrNull()
            if (element is JsonPrimitive) {
                element.intOrNull?.let { return it }
                return parseStatusString(element.content)
            }
        }
        return runCatching { decoder.decodeInt() }.getOrDefault(1)
    }

    private fun parseStatusString(raw: String): Int = when (raw.lowercase().trim()) {
        "0", "down", "disabled", "broken", "inactive", "false" -> 0
        "2", "slow" -> 2
        "3", "beta", "beta_only", "beta only" -> 3
        "1", "ok", "true" -> 1
        else -> 1
    }
}

/**
 * Status int as the following:
 * 0: Down
 * 1: Ok
 * 2: Slow
 * 3: Beta only
 */
@Serializable
data class SitePlugin(
    // Url to the .cs3 file
    @SerialName("url") val url: String = "",
    // Status to remotely disable the provider
    @Serializable(with = PluginStatusIntSerializer::class)
    @SerialName("status") val status: Int = 1,
    // Integer over 0, any change of this will trigger an auto update
    @SerialName("version") val version: Int = 1,
    // Unused currently, used to make the api backwards compatible?
    // Set to 1
    @SerialName("apiVersion") val apiVersion: Int = 1,
    // Name to be shown in app
    @SerialName("name") val name: String = "",
    // Name to be referenced internally. Separate to make name and url changes possible
    @SerialName("internalName") val internalName: String = "",
    @SerialName("authors") val authors: List<String> = emptyList(),
    @SerialName("description") val description: String? = null,
    // Might be used to go directly to the plugin repo in the future
    @SerialName("repositoryUrl") val repositoryUrl: String? = null,
    // These types are yet to be mapped and used, ignore for now
    @SerialName("tvTypes") val tvTypes: List<String>? = null,
    // Most often a language tag like "en" or "zh-TW"
    @SerialName("language") val language: String? = null,
    @SerialName("iconUrl") val iconUrl: String? = null,
    // Automatically generated by the gradle plugin
    @SerialName("fileSize") val fileSize: Long? = null,
    @SerialName("fileHash") val fileHash: String? = null,
)
