package com.lagradost.cloudstream3.plugins

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Status int as the following:
 * 0: Down
 * 1: Ok
 * 2: Slow
 * 3: Beta only
 */
@Serializable
data class SitePlugin(
    // Url to the .cs3 file
    @SerialName("url") val url: String,
    // Status to remotely disable the provider
    @SerialName("status") val status: Int,
    // Integer over 0, any change of this will trigger an auto update
    @SerialName("version") val version: Int,
    // Unused currently, used to make the api backwards compatible?
    // Set to 1
    @SerialName("apiVersion") val apiVersion: Int,
    // Name to be shown in app
    @SerialName("name") val name: String,
    // Name to be referenced internally. Separate to make name and url changes possible
    @SerialName("internalName") val internalName: String,
    @SerialName("authors") val authors: List<String>,
    @SerialName("description") val description: String?,
    // Might be used to go directly to the plugin repo in the future
    @SerialName("repositoryUrl") val repositoryUrl: String?,
    // These types are yet to be mapped and used, ignore for now
    @SerialName("tvTypes") val tvTypes: List<String>?,
    // Most often a language tag like "en" or "zh-TW"
    @SerialName("language") val language: String?,
    @SerialName("iconUrl") val iconUrl: String?,
    // Automatically generated by the gradle plugin
    @SerialName("fileSize") val fileSize: Long?,
    @SerialName("fileHash") val fileHash: String?,
)
